#include "shared.h"
#include "i8080.h"

/* Intel 8080 Codegen Templates */

struct templ templand[] {
	CON,0,0,DEITHER,0,
		"lxi G,V\n",
	LOAD,CON,0,DHL,TLSKIP,
		"lhld LV\n",
	LOAD,0,0,DHL,0,
		"mov a,m\ninx h\nmov h,m\nmov l,a\n",
	CLOAD,CON,0,DEITHER,TLSKIP,
		"mvi G,0\nlda LV\nmov GL,a\nora a\njp T0\ndcr G\nT0:",
	CLOAD,0,0,DEITHER,0,
		"mov GL,m\nmvi G,0\nmov a,GL\nora a\njp T0\ndcr G\nT0:",
	ASSIGN,CON,0,DHL,TLSKIP,
		"shld LV\n",
	ASSIGN,0,0,DBIN,0,
		"mov m,e\ninx h\nmov m,d\nxchg\n",
	CASSIGN,CON,0,DEITHER,TLSKIP,
		"mov a,GL\nsta LV\n",
	CASSIGN,0,0,DBIN,0,
		"mov m,e\nxchg\n",
	QUEST,0,0,DSPECIAL,0,
		0,
	COLON,0,0,DSPECIAL,0,
		0,
	LOGOR,0,0,DSPECIAL,0,
		"mov a,l\nora h\njnz T0\n",
	LOGAND,0,0,DSPECIAL,0,
		"mov a,l\nora h\njz T0\n",
	OR,0,0,DBIN,TCOMMUT,
		"mov a,l\nora e\nmov l,a\nmov a,h\nora d\nmov h,a\n",
	EOR,0,0,DBIN,TCOMMUT,
		"mov a,l\nxra e\nmov l,a\nmov a,h\nxra d\nmov h,a\n",
	AND,0,0,DBIN,TCOMMUT,
		"mov a,l\nana e\nmov l,a\nmov a,h\nana d\nmov h,a\n",
	/* EQU */
	/* NEQU */
	/* LESS */
	LESS,0,0,DBIN,0,
		"call cless\n",
	GREAT,0,0,DBIN,0,
		"call cgreat\n",
	LEQU,0,0,DBIN,0,
		"call clequ\n",
	GEQU,0,0,DBIN,0,
		"call cgequ\n",
	RSHIFT,0,0,DBIN,0,
		"call crshift\n",
	LSHIFT,0,CON,DHL,TRSKIP,
		"RPdad h\nP",
	LSHIFT,0,0,DBIN,0,
		"T0:mov a,e\nora d\njz T1\ndad h\ndcx d\njmp T0\nT1:",
	ADD,0,0,DBIN,TCOMMUT,
		"dad d\n",
	SUB,0,0,DBIN,0,
		"mov a,l\nsub e\nmov l,a\nmov a,h\nsbb d\nmov h,a\n",
	MULT,0,0,DBIN,TCOMMUT,
		"call cmult\n",
	DIV,0,0,DBIN,0,
		"call cdiv\n",
	MOD,0,0,DBIN,0,
		"call cmod\n",
	NEG,0,0,DEITHER,0,
		"mov a,l\ncma\nmov l,a\nmov a,h\ncma\nmov h,a\ninx h\n",
	LOGNOT,0,0,DHL,0,
		"lxi d,0\nmov a,l\nora h\njnz T1\ninx d\nT1:xchg\n",
	LOG,0,0,DHL,0,
		"lxi d,0\nmov a,l\nora h\njz T1\ninx d\nT1:xchg\n",
	COMPL,0,0,DEITHER,0,
		"mov a,l\ncma\nmov l,a\nmov a,h\ncma\nmov h,a\n",
	REG,0,0,DEITHER,0,
		"lxi G,regV\n",
	PREINC,0,0,DSPECIAL,0,
		"lxi d,V\nmov a,m\nadd e\nmov e,a\nmov m,a\n\
inx h\nmov a,m\nadc d\nmov d,a\nmov m,a\nxchg\n",
	PREDEC,0,0,DSPECIAL,0,
		"lxi d,V\nmov a,m\nsub e\nmov e,a\nmov m,a\n\
inx h\nmov a,m\nsbb d\nmov d,a\nmov m,a\nxchg\n",
	POSTINC,0,0,DSPECIAL,0,
		"mov a,m\nmov e,a\nadi <V\nmov m,a\n\
inx h\nmov a,m\nmov d,a\naci >V\nmov m,a\nxchg\n",
	POSTDEC,0,0,DSPECIAL,0,
		"mov a,m\nmov e,a\nsui <V\nmov m,a\n\
inx h\nmov a,m\nmov d,a\nsbi >V\nmov m,a\nxchg\n",
	CPREINC,0,0,DHL,0,
		"mov m,a\nadi V\nmov m,a\nmov l,a\nmvi h,0\njp T1\ndcr h\nT1:",
	CPREDEC,0,0,DHL,0,
		"mov m,a\nsui V\nmov m,a\nmov l,a\nmvi h,0\njp T1\ndcr h\nT1:",
	CPOSTINC,0,0,DSPECIAL,0,
		"mvi d,0\nmov e,m\nmov a,e\nora a\njp T1\ndcr d\nT1:\
adi V\nmov m,a\nxchg\n",
	CPOSTDEC,0,0,DSPECIAL,0,
		"mvi d,0\nmov e,m\nmov a,e\nora a\njp T1\ndcr d\nT1:\
sui V\nmov m,a\nxchg\n",
	CALL,0,CON,DSPECIAL,TRSKIP,
		"call RV\n",
	CALL,0,0,DSPECIAL,0,
		"call ccall\n",
	ARG,0,0,DSPECIAL,0,
		"push h\n",
	/* TOFLT */
	/* TOINT */
	ULESS,0,0,DBIN,0,
		"call culess\n",
	UGREAT,0,0,DBIN,0,
		"call cugreat\n",
	ULEQU,0,0,DBIN,0,
		"call culequ\n",
	UGEQU,0,0,DBIN,0,
		"call cugequ\n",
	AUTO,0,0,DHL,0,
		"lxi h,V\ndad b\n",
	ASNADD,0,0,DBIN,0,
		"call casnadd\n",
	ASNSUB,0,0,DBIN,0,
		"call casnsub\n",
	ASNMULT,0,0,DBIN,0,
		"call casnmult\n",
	ASNDIV,0,0,DBIN,0,
		"call casndiv\n",
	ASNMOD,0,0,DBIN,0,
		"call casnmod\n",
	ASNRSHIFT,0,0,DBIN,0,
		"call casnrshift\n",
	ASNLSHIFT,0,0,DBIN,0,
		"call casnlshift\n",
	ASNAND,0,0,DBIN,0,
		"call casnand\n",
	ASNEOR,0,0,DBIN,0,
		"call casneor\n",
	ASNOR,0,0,DBIN,0,
		"call casnor\n",
	CASNADD,0,0,DBIN,0,
		"call ccasnadd\n",
	CASNSUB,0,0,DBIN,0,
		"call ccasnsub\n",
	CASNMULT,0,0,DBIN,0,
		"call ccasnmult\n",
	CASNDIV,0,0,DBIN,0,
		"call ccasndiv\n",
	CASNMOD,0,0,DBIN,0,
		"call ccasnmod\n",
	CASNRSHIFT,0,0,DBIN,0,
		"call ccasnrshift\n",
	CASNLSHIFT,0,0,DBIN,0,
		"call ccasnlshift\n",
	CASNAND,0,0,DBIN,0,
		"call ccasnand\n",
	CASNEOR,0,0,DBIN,0,
		"call ccasneor\n",
	CASNOR,0,0,DBIN,0,
		"call ccasnor\n",
	COMMA,0,0,DSPECIAL,0,
		"",

	0,0,0,0,0,0
};
